require 'tmpdir'
require_relative '../lib/darknet'

version = Darknet::VERSION
build_dir = Dir.mktmpdir("darknet-build")
archive_path = "darknet-#{version}.tar.gz"
source_path = "darknet-#{version}"
compiled_path = Darknet.dir

task :build_dir do
	Dir.chdir build_dir
end

task :fetch do
	url = "https://github.com/AlexeyAB/darknet/archive/#{version}.tar.gz"

	unless File.exist? archive_path
		sh "wget #{url} -O #{archive_path}"
	end
end

task :extract do
	unless File.exist? source_path
		sh "tar -xvf #{archive_path}"
	end
end

task :build do
	Dir.chdir source_path do
		sh "make OPENMP=1"
	end
	FileUtils.mv source_path, compiled_path
end

task :clean do
	FileUtils.rm_rf archive_path
	FileUtils.rm_rf source_path
	FileUtils.rm_rf build_dir
end

task :default => [:build_dir, :fetch, :extract, :build]
